### ISSUE TITLE
epd-fuse.service issues

### ISSUE THREAD

**Issue by kulpio** [PiSupply/PaPiRus#199]
Hi all,

I installed a new Raspbian image. I ran the automatic installation of the PaPiRus. 
After the reboot, when I go to test the papirus or print "clock" it asks me to set screen size (which I already did in the installation). Still, I go to config and set it again. Then I get the following error:

`pi@raspberrypi:~ $ sudo papirus-config
Failed to stop epd-fuse.service: Unit epd-fuse.service not loaded.
/usr/local/bin/papirus-set: line 20: /etc/default/epd-fuse: No such file or directory
sed: can't read /etc/default/epd-fuse: No such file or directory

2.7
sed: can't read /etc/default/epd-fuse: No such file or directory
Failed to start epd-fuse.service: Unit epd-fuse.service not found.
Failed to enable unit: File epd-fuse.service: No such file or directory
Failed to start epd-fuse.service: Unit epd-fuse.service not found.
`
and this is what happens when I "test":

`pi@raspberrypi:~ $ sudo papirus-test
Traceback (most recent call last):
  File "/usr/local/bin/papirus-test", line 69, in <module>
    papirus = Papirus()
  File "/usr/local/lib/python3.5/dist-packages/papirus/epd.py", line 83, in __init__
    with open(os.path.join(self._epd_path, 'version')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/dev/epd/version'
`

This what I get when I run the systemctl status for the epd-fude:

`sudo systemctl status epd-fuse
Unit epd-fuse.service could not be found.
`
FYI I have the Raspbian Stretch version

Would anyone have an idea? I spent most of my day trying to get it to work ;(

Cheers

**Comment by tvoverbeek** [comment]
It seems the installation of the epd-fuse driver and service failed for some reason.
Try to rerun papirus-setup (with sudo). Should be located in /usr/bin.
If not use the github version: https://github.com/PiSupply/PaPiRus/blob/master/bin/papirus-setup
Check for error messages.
